

stages:
    - build
    - test
   # - deploy

build1:
  stage: build
  script:
    - mvn install

test1:
  stage: test
  script: mvn verify

#deploy1:
 # stage: deploy
  #script:
   # - mvn org.codehaus.cargo:cargo-maven2-plugin:run


