

stages:
    - build
    - test
    - deploy

test1:
  stage: test
  script: mvn verify

build1:
  stage: build
  script:
    - mvn install

deploy1:
  stage: deploy
  script:
    - mvn clean deploy -Dmaven.test.skip=true


